- name: remove preinstalled git
  yum:
    name=git
    state=absent

- name: get git archive
  get_url:
    url=https://www.kernel.org/pub/software/scm/git/git-{{ GIT_VERSION }}.tar.gz
    dest=~
    validate_certs={{ VALIDATE_CERTS }}

- name: unpack git source code
  unarchive:
    src=~/git-{{ GIT_VERSION }}.tar.gz
    dest=/usr/src
    copy=no

- name: compile and install git
  shell: make prefix=/usr/local all install
  args:
    chdir: /usr/src/git-{{ GIT_VERSION }}
    creates: /usr/local/bin/git
