- include: install_packages.yml
- include: install_git.yml
- include: install_luasandbox.yml
- include: install_composer.yml
- include: configure_selinux.yml
- include: create_dirs.yml
- include: configure_php.yml
- include: configure_apache.yml
- include: configure_squid.yml
